version: '3.1'
services:
  stats-server:
    build: statistic/service/
    image: ewm_statistic_service_image
    container_name: ewm-statistic-service-container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm-stat
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db-container
    volumes:
      - /var/lib/postgresql/stats/
    ports:
      - "6543:5432"
    environment:
      - POSTGRES_DB=ewm-stat
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  ewm-service:
    build: main/
    image: ewm_main_service_image
    container_name: ewm-main-service-container
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-server

    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm-db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - STATISTIC_SERVICE_URL=http://stats-server:9090

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-db-container
    volumes:
      - /var/lib/postgresql/main/
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ewm-db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
